services:
  runner:
    container_name: action-runner
    env_file:
      - runner.env
    build:
      context: .
      args:
        - REPO_URL=${REPO_URL}
        - RUNNER_TOKEN=${RUNNER_TOKEN}
        - NAME=${NAME}
    volumes:
      - ./runner_work:/home/runner/_work

volumes:
  runner_work:
