services:
  runner:
    # For custom setup assign CONTAINER_NAME and ENV_FILE in .env
    container_name: ${CONTAINER_NAME:-budu-runner}
    network_mode: host
    build:
      context: .
      args:
        - ENV_FILE=${ENV_FILE:-runner.env}
    environment:
      - ENV_FILE=${ENV_FILE:-runner.env}
